load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_static_library")
load("//tools/bazel:rust_cxx_bridge.bzl", "rust_cxx_bridge")

rust_binary(
    name = "demo",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    deps = [
        ":blobstore-sys",
        ":bridge",
        "//:cxx",
    ],
)

rust_static_library(
    name = "demolib",
    srcs = ["src/main.rs"],
    edition = "2021",
    deps = [
        ":blobstore-sys",
        ":bridge",
        "//:cxx",
    ],
)

cc_binary(
    name = "democc",
    srcs = ["src/main.cc"],
    copts = ["-std=c++17"],
    deps = [
        ":blobstore-sys",
        ":bridge",
        ":demolib",
        "//:cxx",
    ],
)

rust_cxx_bridge(
    name = "bridge",
    src = "src/main.rs",
    deps = [":blobstore-include"],
)

cc_library(
    name = "blobstore-sys",
    srcs = ["src/blobstore.cc"],
    deps = [
        ":blobstore-include",
        ":bridge/include",
    ],
)

cc_library(
    name = "blobstore-include",
    hdrs = ["include/blobstore.h"],
    deps = ["//:core"],
)
